language: php
php:
    - '7.2'
    - '7.3'
install:
    - composer self-update
    - composer install
    - export PATH="$(pwd)/vendor/bin:$PATH"
script:
    - codecept run unit
notifications:
    email: false