language: php
php:
    - '5.6'
    - '7.0'
install:
    - composer self-update
    - composer install
    - export PATH="$(pwd)/vendor/bin:$PATH"
script:
    - codecept run unit
notifications:
    email: false